"""Builds the Ryzer Gen fission station calculator's 3D model from a Ryzer Gen checkout:
the formed station's mesh (assets/ryzergen/station/fission_station.json, drawn by the mod's
art/tools/fission_concept.py) and the textures it and the rods use, packed into one atlas.

    python scripts/ryzer-gen-station-model.py <path to ryzer-gen checkout>

Writes site/tools/ryzer-gen/fission-station-calculator/station-model.js. Ryzer Gen is MIT licensed.
Needs Pillow.
"""
import base64, io, json, sys
from pathlib import Path
from PIL import Image

src = Path(sys.argv[1]) / "mod/src/main/resources/assets/ryzergen"
out = Path(__file__).resolve().parent.parent / "site/tools/ryzer-gen/fission-station-calculator/station-model.js"
design = json.loads((src / "station/fission_station.json").read_text())

# The rods are drawn in code (StationRenderer.rods), from these textures.
textures = dict(design["textures"])
for name in ["steel_dark", "copper", "lead", "fuel_pin", "fuel_pin_off", "spacer", "nozzle", "cherenkov", "moderator", "control"]:
    textures.setdefault(name, "ryzergen:block/" + ("microreactor/" if name in ("steel_dark", "copper", "lead") else "station/") + name)

# Shelf-pack every texture (animated strips: first frame) with a 1 px extruded border, so nearest
# sampling at a tile's edge never picks up its neighbour.
images = {}
for name, loc in textures.items():
    im = Image.open(src / "textures" / (loc.split(":")[1] + ".png")).convert("RGBA")
    if im.height > im.width * 2 and im.height % im.width == 0:
        im = im.crop((0, 0, im.width, im.width))
    images[name] = im
W = 256
x = y = row = 0
tiles = {}
for name, im in sorted(images.items(), key=lambda kv: -kv[1].width):
    w, h = im.width + 2, im.height + 2
    if x + w > W:
        x, y, row = 0, y + row, 0
    tiles[name] = (x + 1, y + 1, im.width, im.height)
    x += w
    row = max(row, h)
H = 1
while H < y + row:
    H *= 2
atlas = Image.new("RGBA", (W, H))
for name, (tx, ty, tw, th) in tiles.items():
    im = images[name]
    padded = Image.new("RGBA", (tw + 2, th + 2))
    padded.paste(im, (1, 1))
    padded.paste(im.crop((0, 0, tw, 1)), (1, 0)); padded.paste(im.crop((0, th - 1, tw, th)), (1, th + 1))
    padded.paste(padded.crop((1, 0, 2, th + 2)), (0, 0)); padded.paste(padded.crop((tw, 0, tw + 1, th + 2)), (tw + 1, 0))
    atlas.paste(padded, (tx - 1, ty - 1))
buf = io.BytesIO()
atlas.save(buf, "PNG", optimize=True)

names = sorted(tiles)
index = {n: i for i, n in enumerate(names)}
r = lambda v: round(v, 2) if v % 1 else int(v)
groups = {}
for group, quads in design["quads"].items():
    flat = []
    for q in quads:
        flat.append(index[q[0]])
        for c in range(4):
            flat.extend(r(v) for v in q[1 + c * 5: 6 + c * 5])
    groups[group] = flat

model = {
    "source": "Ryzer Gen fission_station.json (MIT)",
    "atlas": "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode(),
    "size": [W, H],
    "tiles": [list(tiles[n]) for n in names],
    "names": names,
    "emissive": design["emissive"],
    # each quad: tile, then 4 corners of x, y, z (design pixels) and u, v (0 to 16 across the texture)
    "groups": groups,
}
out.write_text("/* Generated by scripts/ryzer-gen-station-model.py from Ryzer Gen's own station model and textures\n"
               "   (github.com/MultiRyzer/ryzer-gen, MIT licensed). Do not edit by hand. */\n"
               "window.RG_STATION=" + json.dumps(model, separators=(",", ":")) + ";\n")
print(out, out.stat().st_size, "bytes;", sum(len(q) for q in design["quads"].values()), "quads; atlas", W, "x", H)
